/*
 * NOTE: This file is generated by the bitmap-font tool, use it to update it.
 */
#ifndef __BITMAP_FONT_DATA__
#define __BITMAP_FONT_DATA__
#include <stdint.h>

extern uint8_t bitmapFontCharSet[130][190];
#endif
    