# Thread & process structure documentation
:toc: left
:last-update-label!:
:source-highlighter: prettify 
include::../common/homelink.adoc[]

:numbered:
[[Threads]]
Threads
-------
A thread is a single stream of code execution. Threads hold information about
their current state and their configuration. All threads run solely in
user-space, there are no threads running in kernel-space for design reasons.

Each thread has a unique id of type `g_tid`. This id can be obtained from within
the thread using `<<libapi#g_get_tid,g_get_tid>>`.

Each thread has its own user- and kernel-space stack. See the
<<memory#Stacks,stack section>> of the memory layout documentation for details.


Types of threads
~~~~~~~~~~~~~~~~
The following constants of type `g_thread_type` denote types of threads.
[options="header"]
|==========================================================
| Identifier			| Description
| G_THREAD_TYPE_MAIN	| Main thread of a process
| G_THREAD_TYPE_SUB		| Sub-thread of a process
| G_THREAD_TYPE_VM86	| VM86 thread
|==========================================================



Creating a thread
~~~~~~~~~~~~~~~~~
To create a thread, the `<<libapi#g_create_thread,g_create_thread>>` API function
is used. This function must be supplied with an address pointing to code that the
thread shall execute. Typically, a function name is used as the execution entry.
The variations of this function can also be supplied with a pointer to user data.

A simple example could look like this:

[source,c]
-----
void myThreadedCounter(int* counter) {
	for(;;) {
		(*counter)++;
	}
}

int main(int argc, char** argv) {
	int counter = 0;
	g_create_thread_d(myThreadedCounter, &counter);
	
	for(;;) {
		g_sleep(1000);
		printf("The counter is: %i\n", counter);
	}
}
-----

Internals
^^^^^^^^^
Internally, the thread initialization uses a wrapper function for starting
the thread. First, the `G_SYSCALL_CREATE_THREAD` system call is called
and supplied with a "thread setup routine" and the "user entry" (the function
given to `g_create_thread`).

This setup routine is the first piece of code that is executed from within the
newly created thread, but does initially not know where to start execution.
To get this information, it uses `G_SYSCALL_GET_THREAD_ENTRY` which returns
the user entry to start executing at.

This entire procedure is done to avoid that the kernel must modify the user
stack to put the necessary values on it, but rather do it from within code which
adapts to the calling convention.


Exiting a thread
~~~~~~~~~~~~~~~~
A thread is automatically destroyed once the main function finishes execution.
To stop execution from an arbitrary point, the `<<libapi#g_exit,g_exit>>` API
function can be used.

A single thread can not be killed from a different process; using the
`<<libapi#g_kill,g_kill>>` always causes the entire process to exit.

When the main thread of a <<Processes,process>> dies, all threads of the process
are killed.



[[Processes]]
Processes
---------
A process is a wrapper around one or more threads. It holds information that
is common for all of its threads. Each process has a main thread and can
have multiple child threads.

A process itself has no id, it is identified by the id of the main thread.



[[SecurityLevels]]
Security Levels
---------------
When creating a process, a security level is used to determine what permissions
the threads of the process have. This security level is stored on the process
and applied on thread creation.

Existing security levels
~~~~~~~~~~~~~~~~~~~~~~~~
The following constants of type `g_security_level` denote the different
security levels.
[options="header"]
|==========================================================
| Identifier					| Description
| `G_SECURITY_LEVEL_APPLICATION`| Has no specific permissions.
| `G_SECURITY_LEVEL_DRIVER`		| Has I/O permission level 3 (may use `out` and
		`in` commands to access the CPU I/O ports) and is permitted to
		use a variety of driver-related system calls.
| `G_SECURITY_LEVEL_KERNEL`		| Grants special permissions, for example to use
		the spawning API. Only assigned to the initial system processes like the
		spawner binary.
|==========================================================


