= Ghost System Documentation
Max Schlüssel <lokoxe@gmail.com>
v1.0
:last-update-label!:

About
-----
Welcome to the documentation of the Ghost OS!

Ghost is an operating system for the Intel x86 platform written with almost
all components written from scratch. The kernel follows a pure microkernel
design. This document contains conceptual and technical documentation about
the system.

NOTE: This file is supposed to be compiled with AsciiDoctor
(http://asciidoctor.org/), see the scripts `generate.sh` and `generate.bat`.

The contents of this documentation are split in sections for each system
component. On the top of each page there's a link back to this home page.

* *Kernel section* contains documentation about the kernel itself.
	** <<threads#,Threads section>> contains everything about processes and threading
	** <<memory#,Memory layout documentation>> explains the thread memory layout
* *<<compilation#,Building>>* - toolchain & system building instructions
* *<<libapi#,libapi>>* - documentation for the kernel API wrapper library
* *<<libc#,libc>>* - documentation for the C library implementation
* *<<ramdisk-format#,Ramdisk>>* - documentation about the Ramdisk format & generation
* *<<port#,port.sh>>* - manual for the porting utility
* *<<spawning#,Spawning>>* about process creation
