name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build in Docker container
        run: |
          docker run \
            -v ${{ github.workspace }}:/ghost/source \
            ghcr.io/maxdev1/ghost-toolchain-64:1.0 \
            /bin/bash -c "cd /ghost/source && ./build.sh --ci"
          if [ $? -ne 0 ]; then
            echo "Build failed"
            exit 1
          fi

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/ghost.iso
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
